config/routes.rb
ForMom3::Application.routes.draw do
  get "applyings/apply_here"
  get 'home/index'
  root 'home#index'

  devise_for :users
  patch '/users/:id', :to => 'home#index', :as => :user

  resources :schools do
    resources :prompts
  end

  resources :responses

  

end

app/models/applying.rb
class Applying < ActiveRecord::Base
  belongs_to :school
  belongs_to :user
end

app/models/prompt.rb
class Prompt < ActiveRecord::Base
  validates :question, presence: true

  belongs_to :school
  has_many :responses
end

app/models/response.rb
class Response < ActiveRecord::Base
  validates :comments, presence: true

  belongs_to :prompt
  belongs_to :user
end

app/models/school.rb
class School < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2 }

  has_many :applyings
  has_many :users, through: :applyings

  has_many :prompts
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :applyings
  has_many :schools, through: :applyings

  has_many :responses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :high_school, :grad_year) }
  end
end

app/controllers/applyings_controller.rb
class ApplyingsController < ApplicationController
  def apply_here
    @id = params[:school_id]

    if current_user.schools.find_by id: @id
      flash[:notice] = "You're already applying here"
    else
      current_user.schools << School.find(@id)
    end

    redirect_to root_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_filter :authenticate_user!

  def index
  end
end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  def create
    @school = School.find(params[:school_id])
    @prompt = @school.prompts.create(prompt_params)

    redirect_to :back
  end

private
  def prompt_params
    params.required(:prompt).permit(:question)
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def create
    @response = Response.create(response_params)

    redirect_to :back
  end

private
  def response_params
    params.required(:response).permit(:comments, :user_id, :prompt_id, :student_id)
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @schools = School.all
  end

  def new
    @school = School.new
  end

  def create
    @school = School.find_or_create_by(school_params)
    @school.save
    
    redirect_to :back
  end

  def show
    @school = School.find(params[:id])
  end

  def destroy
    @school = School.find(params[:id])
    @school.destroy

    redirect_to schools_path
  end

private
  def school_params
    params.required(:school).permit(:name, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applyings_helper.rb
module ApplyingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prompts_helper.rb
module PromptsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/home/_admin.html.erb
<h1>Welcome, Randi!</h1><hr>

<% User.all.each do |user| %>
  <% if user.admin? != true %>
    <h3><%= user.name %> (<%= user.email %>) from <%= user.high_school %>, class of <%= user.grad_year %></h3>
    <% user.schools.each do |school| %>
      <h2><%= link_to school.name, school_path(school) %></h2>
      <% if school.prompts.length > 0 %>
        <table style="text-align:left;">
          <tr>
            <th style="width:200px;">Essay Prompt</th>
            <th style="width:200px;">Newest response comments</th>
            <th style="width:200px;">Newest responder</th>
            <th style="width:50px;">Status</th>
            <th>Add a response</th>
          </tr>
          <% school.prompts.each do |prompt| %>
            <tr>
              <td><%= prompt.question %></td>
              <% @relevant_responses = Response.where("prompt_id='#{prompt.id}' AND (user_id='#{user.id}' OR student_id='#{user.id}')") %>
              <% if @relevant_responses.length > 0 %>
                <td><%= @relevant_responses.last.comments %></td>
                <td><%= @relevant_responses.last.user.name %></td>
              <% else %>
                <td><i>No responses yet</i></td>
                <td>N/A</td>
              <% end %>
              <td>Status</td>
              <%= form_for(Response.new) do |f| %>
                <td><%= f.text_field :comments %><%= f.submit %></td>
                <span style="visibility:hidden; height:0px;"><%= f.label :user_id %><%= f.text_field :user_id, :value => current_user.id %><%= f.label :prompt_id %><%= f.text_field :prompt_id, :value => prompt.id %><%= f.text_field :student_id, :value => user.id %></span>
              <% end %>
            </tr>
          <% end %>
        </table>
      <% end %>
      <%= form_for([school, school.prompts.build]) do |f| %>
        <p>
          <%= f.label 'Add a prompt:' %><br />
          <%= f.text_field :question, :size => "70x10" %>
        </p>
        <p><%= f.submit %></p>
      <% end %>
      <br />
    <% end %>
    <hr>
  <% end %>
<% end %>

app/views/home/_student.html.erb
<h1>Welcome, <%= current_user.name %>!</h1>
<p><%= current_user.high_school %>, class of <%= current_user.grad_year %></p>

<% if current_user.schools.length > 0 %>
  <h2>You're applying to these schools:</h2>
  <ol>
  <% current_user.schools.each do |school| %>
    <li><%= link_to school.name, school_path(school) %></li>
    <ul><% school.prompts.each do |prompt| %>
      <li><%= prompt.question %></li>
      <% @relevant_responses = Response.where("prompt_id='#{prompt.id}' AND (user_id='#{current_user.id}' OR student_id='#{current_user.id}')") %>
      <ul><% @relevant_responses.each do |response| %>
        <li><%= response.comments %></li>
      <% end %>
      <% if @relevant_responses.length == 0 %>
        <i>No responses yet</i>
      <% end %>
      <%= form_for(Response.new) do |f| %>
        <p>
          <%= f.label "Add a response: " %><%= f.text_field :comments %>
        </p>
        <p><%= f.submit %></p>
        <p style="visibility:hidden; height:0px;">
          <%= f.label :user_id %><%= f.text_field :user_id, :value => current_user.id %><%= f.label :prompt_id %><%= f.text_field :prompt_id, :value => prompt.id %>
        </p>
      <% end %></ul>
    <% end %></ul>
    <%= form_for([school, school.prompts.build]) do |f| %>
      <p>
        <%= f.label 'Add a prompt:' %><br />
        <%= f.text_field :question, :size => "70x10" %>
      </p>
      <p><%= f.submit %></p>
    <% end %>
  <% end %>
  </ol>

  <h2>Apply to more schools</h2>
<% else %>
  <h2>Pick some schools to apply to!</h2>
<% end %>
  <% School.all.each do |school| %>
    <% if !current_user.schools.find_by id: school.id %>
      <p><%= school.name %> | <%= link_to 'Apply here', {:controller => 'applyings', :action => 'apply_here', :school_id => school.id}, :method => :get %>
      </p>
    <% end %>
  <% end %>

<h3>Don't see what you're looking for?</h3>
<p>Add the full name of the school below and then click apply in the list above</p>
<% School.new do |school| %>
  <%= form_for(school) do |f| %>
    <p>
      <%= f.label 'Name:' %>
      <%= f.text_field :name %>
      <%= f.submit 'Add school'%>
    </p>
  <% end %>
<% end %>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <p><%= link_to 'Log out', destroy_user_session_path, method: :delete %></p>
<% else %>
  <p><%= link_to 'Log in', new_user_session_path %></p>
  <p><%= link_to 'Sign up', new_user_registration_path %></p>
<% end %>

<% if user_signed_in? && current_user.admin? %>
  <%= render :partial => 'admin' %>
<% elsif user_signed_in? && !current_user.admin? %>
  <%= render :partial => 'student' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForMom3</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? && current_user.admin? %>
  <p>You're logged in! As an <strong>admin</strong>! <%= current_user.email %></p>
<% elsif user_signed_in? && !current_user.admin? %>
  <p>You're logged in! As a <strong>student</strong>! <%= current_user.email %></p>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/schools/index.html.erb
<h1>List all schools</h1>

<% if @schools.length > 0 %>
  <% @schools.each do |school| %>
    <p><%= school.name %>, <%= school.id %>, <%= link_to 'Delete', school_path(school),
                      method: :delete, data: { confirm: 'Are you sure?' } %></p>
  <% end %>
<% else %>
  <p>No schools yet</p>
<% end %>

<p><%= link_to 'Add a school', new_school_path %></p>

app/views/schools/show.html.erb
<h1><%= @school.name %></h1>

<% if user_signed_in? && current_user.admin? %>
  <%= render :partial => 'admin' %>
<% elsif user_signed_in? && !current_user.admin? %>
  <% if !current_user.schools.find_by id: @school.id %>
    <h2><%= link_to 'Apply here', {:controller => 'applyings', :action => 'apply_here', :school_id => @school.id}, :method => :get %></h2>
  <% end %>
  <%= render :partial => 'student' %>
<% end %>

<p><%= link_to '<< GO HOME', root_url %></p>

<% if user_signed_in? && current_user.admin? %>
  <h2>Students applying here:</h2>
  <% if @school.users.length > 0 %>
    <ul>
      <% @school.users.each do |user| %>
        <li><%= link_to user.name, user_path(user) %></li>
      <% end %>
    </ul>
  <% else %>
    <p><i>No one has yet chosen to apply here</i></p>
  <% end %>
<% end %>

<h2>Essay prompts</h2>
<% if @school.prompts.length == 0 %>
  <p><i>You haven't added any prompts for this school</i></p>
<% end %>

<% @school.prompts.each do |prompt| %>
  <p>
    <strong><%= prompt.question %></strong>
  </p>
  </br>
<% end %>